### ISSUE TITLE
Interpreter::exitSmalltalk fails to dump counters

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/DolphinVM#15]
In the Debug configuration Dolphin attempts to provide information on the following:
 * `primitiveCounters`
 * `byteCodeCounters`
 * `byteCodePairs`

And finds that they are unresolved externals. Note `decode.cpp` from 1654 to the end.

**Comment by blairmcg** [comment]
These arrays of counters are defined in the assembly code, which needs to assembled with _DEBUG defined for a debug build. E.g. primitiveCounters is defined as _primitiveCounters in primasm.asm line 548

**Comment by blairmcg** [comment]
There is a fix for this as part of my VS2015 standup in the branch blairmc/vs2015vm

**Comment by blairmcg** [comment]
Fixed as of fadbbe7

**Comment by jgfoster** [comment]
It appears to me that primitiveCounters is still not being printed. See decode.cpp(1690).

**Comment by blairmcg** [comment]
Yeah, missed those. Thanks
